// Helpers/ManjosPrice.js

const priceData = [
    {
      id: 1028,
      type: "resto",
      name: "Confit",
      price: 20,
      number: 1,
      option: "",
    },
    {
      id: 1029,
      type: "resto",
      name: "Magret",
      price: 25,
      number: 1,
      option: "",
    },
    {
      id: 1030,
      type: "resto",
      name: "1/2 Magret",
      price: 18,
      number: 1,
      option: "",
    },
    {
      id: 1003,
      type: "resto",
      name: "Tartare",
      price: 20,
      number: 1,
      option: "",
    },
    {
      id: 1005,
      type: "resto",
      name: "Cassoulet",
      price: 17.5,
      number: 1,
      option: "",
    },
    {
      id: 1006,
      type: "resto",
      name: "Tarte",
      price: 16,
      number: 1,
      option: "",
    },
    {
      id: 1007,
      type: "resto",
      name: "Saucisse",
      price: 12,
      number: 1,
      option: "",
    },
    {
      id: 1032,
      type: "resto",
      name: "Saucisse PN",
      price: 18,
      number: 1,
      option: "",
    },
    {
      id: 1031,
      type: "resto",
      name: "Rouleau",
      price: 30,
      number: 1,
      option: "",
    },
    {
      id: 1009,
      type: "resto",
      name: "Salade chèvre",
      price: 16,
      number: 1,
      option: "",
    },
    {
      id: 1017,
      type: "resto",
      name: "Salade crudité",
      price: 14,
      number: 1,
      option: "",
    },
    {
      id: 1024,
      type: "resto",
      name: "Frites",
      price: 5,
      number: 1,
      option: "",
    },
    {
      id: 1027,
      type: "resto",
      name: "Dessert",
      price: 6,
      number: 1,
      option: "",
    },
    {
      id: 1008,
      type: "resto",
      name: "Dessert",
      price: 7,
      number: 1,
      option: "",
    },
    {
      id: 1010,
      type: "resto",
      name: "Soupe",
      price: 6,
      number: 1,
      option: "",
    },
    {
      id: 1013,
      type: "resto",
      name: "Mini chèvre",
      price: 6,
      number: 1,
      option: "",
    },
    {
      id: 1011,
      type: "resto",
      name: "Menu enfant",
      price: 8.5,
      number: 1,
      option: "",
    },
    {
      id: 1012,
      type: "resto",
      name: "Menu enfant",
      price: 9.5,
      number: 1,
      option: "",
    },
    {
      id: 1014,
      type: "resto",
      name: "Trio PN",
      price: 14,
      number: 1,
      option: "",
    },
    {
      id: 1015,
      type: "resto",
      name: "Charcuterie",
      price: 16,
      number: 1,
      option: "",
    },
    {
      id: 1018,
      type: "resto",
      name: "Maxi saucisse",
      price: 20,
      number: 1,
      option: "",
    },
    {
      id: 1019,
      type: "resto",
      name: "Maxi Confit",
      price: 30,
      number: 1,
      option: "",
    },
    {
      id: 1033,
      type: "resto",
      name: "Maxi Carne",
      price: 35,
      number: 1,
      option: "",
    },
    {
      id: 1023,
      type: "resto",
      name: "Maxi tartare",
      price: 28,
      number: 1,
      option: "",
    },
    {
      id: 1081,
      type: "boisson",
      name: "Limonade",
      price: 2.5,
      number: 1,
      option: "",
    },
    {
      id: 1082,
      type: "boisson",
      name: "Thé / crème",
      price: 3,
      number: 1,
      option: "",
    },
    {
      id: 1093,
      type: "boisson",
      name: "Café",
      price: 1.8,
      number: 1,
      option: "",
    },
    {
      id: 1083,
      type: "boisson",
      name: "Sirop",
      price: 2,
      number: 1,
      option: "",
    },
    {
      id: 1088,
      type: "boisson",
      name: "Glace",
      price: 2,
      number: 1,
      option: "",
    },
    {
      id: 1090,
      type: "boisson",
      name: "Glace",
      price: 3.5,
      number: 1,
      option: "",
    },
    {
      id: 1091,
      type: "boisson",
      name: "Glace",
      price: 4,
      number: 1,
      option: "",
    },
    {
      id: 1116,
      type: "boisson",
      name: "Glace",
      price: 4.5,
      number: 1,
      option: "",
    },
    {
      id: 1113,
      type: "boisson",
      name: "Glace",
      price: 5,
      number: 1,
      option: "",
    },
    {
      id: 1089,
      type: "boisson",
      name: "Glace",
      price: 7,
      number: 1,
      option: "",
    },
    {
      id: 1094,
      type: "boisson",
      name: "Soft",
      price: 3,
      number: 1,
      option: "",
    },
    {
      id: 1096,
      type: "boisson",
      name: "Soft bio",
      price: 3.2,
      number: 1,
      option: "",
    },
    {
      id: 1117,
      type: "boisson",
      name: "Abatille",
      price: 4.5,
      number: 1,
      option: "",
    },
    {
      id: 1095,
      type: "boisson",
      name: "Verre de vin",
      price: 2.5,
      number: 1,
      option: "",
    },
    {
      id: 1085,
      type: "boisson",
      name: "Verre de vin",
      price: 3.5,
      number: 1,
      option: "",
    },
    {
      id: 1086,
      type: "boisson",
      name: "1/4 Pichet",
      price: 4,
      number: 1,
      option: "",
    },
    {
      id: 1087,
      type: "boisson",
      name: "1/2 Pichet",
      price: 8,
      number: 1,
      option: "",
    },
    {
      id: 1112,
      type: "boisson",
      name: "1L Pichet",
      price: 16,
      number: 1,
      option: "",
    },
    {
      id: 1109,
      type: "boisson",
      name: "Btl vin bio",
      price: 18,
      number: 1,
      option: "",
    },
    {
      id: 1110,
      type: "boisson",
      name: "Btl collines",
      price: 18,
      number: 1,
      option: "",
    },
    {
      id: 1097,
      type: "boisson",
      name: "Blonde",
      price: 3.5,
      number: 1,
      option: "",
    },
    {
      id: 1098,
      type: "boisson",
      name: "Ambree",
      price: 4,
      number: 1,
      option: "",
    },
    {
      id: 1092,
      type: "boisson",
      name: "Biere bt",
      price: 5,
      number: 1,
      option: "",
    },
    {
      id: 1099,
      type: "boisson",
      name: "Pinte",
      price: 7,
      number: 1,
      option: "",
    },
    {
      id: 1100,
      type: "boisson",
      name: "Pinte ambree",
      price: 8,
      number: 1,
      option: "",
    },
    {
      id: 1080,
      type: "boisson",
      name: "Bière",
      price: 2.8,
      number: 1,
      option: "",
    },
    {
      id: 1101,
      type: "boisson",
      name: "Apero",
      price: 3,
      number: 1,
      option: "",
    },
    {
      id: 1102,
      type: "boisson",
      name: "Digestif",
      price: 5.5,
      number: 1,
      option: "",
    },
    {
      id: 1103,
      type: "boisson",
      name: "Ricard",
      price: 2.5,
      number: 1,
      option: "",
    },
    {
      id: 1104,
      type: "boisson",
      name: "Alcool fort",
      price: 6.5,
      number: 1,
      option: "",
    },
    {
      id: 1105,
      type: "boisson",
      name: "Baby",
      price: 3.5,
      number: 1,
      option: "",
    },
    {
      id: 1107,
      type: "boisson",
      name: "Punch",
      price: 5,
      number: 1,
      option: "",
    },
    {
      id: 1108,
      type: "boisson",
      name: "1L punch",
      price: 20,
      number: 1,
      option: "",
    },
    {
      id: 1114,
      type: "boisson",
      name: "Cocktail",
      price: 8,
      number: 1,
      option: "",
    },
  ];
  
  export default priceData;